name: suspense
dependencies:
  - python=3.9
  - pip=21.0.1
  - psycopg2
  - pip:
      - Django==3
      - django-cors-headers==3
      - djangorestframework==3
      - djangorestframework_simplejwt==4
      - flake8
